spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.234.13.55:3306/halodb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: rootzhou
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  cache:
    type: none
logging:
  level:
    com.leecoder.halo: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
  path: ${user.home}/halo-dev/logs

halo:
  doc-disabled: false
  production-env: false
  auth-enabled: true
  workDir: ${user.home}/halo-dev/
